Add Swift Package Manager support
xmartlabs/Ecno pull request #5
Opened 2020-03-19 17:56 UTC by itsJakov

This should work, although i'm not sure this didn't break CocoaPods support.

2020-03-20 12:45 UTC, mats-claassen requested changes

2020-03-20 12:45 UTC, mats-claassen commented on Package.swift
> +    dependencies: [
You don't need to specify the dependencies key.

2020-03-20 12:45 UTC, mats-claassen commented on Package.swift
> +    name: "Ecno",
Please add a `platform` key that specifies the minimum iOS version supported

2020-03-20 12:48 UTC, mats-claassen commented
Hi @itsJakov Thanks for contributing. I wonder why there are so many changes to the project file. And why you uploaded two new Info.plist files. Supporting Package Manager should only require the Package.Swift file.

2020-03-20 14:07 UTC, itsJakov commented
Adding the `Package.swift` file manually works much better than `swift package init — type library` and `swift package generate-xcodeproj`.

2020-03-23 13:02 UTC, mats-claassen approved these changes

2020-03-23 13:02 UTC, merged